version: '3'
services:
  webapp:
    build: .
    ports:
      - "80:5000"
    depends_on:
      - database
  database:
    image: postgres
    environment:
      POSTGRES_DB: docker-compose-test
      POSTGRES_USER: docker-testuser
      POSTGRES_PASSWORD: 9KJHd2A3_=)(23jkdsHJ