#!/bin/bash

TIMESYNC_FILE=/etc/systemd/timesyncd.conf
MKHOMEDIR_FILE=/usr/share/pam-configs/mkhomedir

#backup old timesyncd file
if [ -f ${TIMESYNC_FILE} ]; then
        cp ${TIMESYNC_FILE} ${TIMESYNC_FILE}.bak
fi

#backup old mkhomedir file
if [ -f ${MKHOMEDIR_FILE} ]; then
        cp ${MKHOMEDIR_FILE} ${MKHOMEDIR_FILE}.bak
fi
